source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'rails', '~> 6.0.5', '>= 6.0.5.1'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.1'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 4.0'
# gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
# gem 'yaaf'
gem 'enum_help'
gem 'ransack'
gem 'kaminari'
# gem 'bcrypt', '~> 3.1.7'
# gem 'ed25519', '>= 1.2', '< 2.0'
# gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'
# # gem 'image_processing', '~> 1.2'
# gem 'unicorn' # アプリケーションサーバのunicorn
gem 'dotenv-rails'
gem 'bootsnap', '>= 1.4.2', require: false

gem 'devise'
gem 'devise-i18n'
gem 'devise-i18n-views'
# gem 'omniauth'
# gem 'omniauth-google-oauth2'
# gem 'omniauth-rails_csrf_protection'
gem "recaptcha", require: "recaptcha/rails"

# gem 'geocoder'
# gem 'gon'

# gem 'payjp'

gem 'faker'
gem 'gimei'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 3.8'
  gem 'factory_bot_rails'
  gem 'launchy'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-doc'
  # gem 'capistrano', '3.6.0'
  # gem 'capistrano-bundler'
  # gem 'capistrano-rails'
  # gem 'capistrano-rbenv'
  # gem 'capistrano3-unicorn'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'letter_opener_web'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rubocop'
  gem 'rubocop-rails'
  # gem 'rails_best_practices'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]